### PR TITLE
Awesome books refactor

### PR DESCRIPTION
**Pull request by djo1975**
Awesome books: refactor to use JavaScript classes
Learning objectives
Use JavaScript classes.
Understand how to use medium-fidelity wireframes to create a UI.
Estimated time: 3.5h
Description
In this project, you will refactor the Awesome books application to use JavaScript classes.

IMPORTANT NOTE: Read all requirements before you start building your project.

General requirements
Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
Make sure that you used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
JavaScript requirements
Follow our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
Project requirements
Use JavaScript classes instead of objects and arrays.
You can use objects and arrays, but do it inside classes.
Create class methods to add and remove books.
Maintain all of the original functionality of the application (i.e. no bugs were introduced while refactoring).
Don't use any library or framework, use only plain JavaScript.
Add CSS styles to the application to make it match this wireframe:
Basic UI

You can use the styles of your choice (colors, fonts, backgrounds, etc.), but try to follow the general layout.
Concentrate on the general layout, rather than the details.

### CODE REVIEW

**Comment by julie-ify** [comment]
Hi @djo1975 and @alicemirigo92, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### There are three coding partners in this group but only two committed to this project. Kindly ensure the third member contributes to this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by djo1975** [comment]
Hi Juliana

We are not sure what is going on with third partner (edited) 

we have just this message from him

hello guys
[4:38 PM] i am sorry did not know i have been moved to another team
[4:38 PM] i tut i was mistakenly switched when i joined the call

He is probably in some other group

**Comment by djo1975** [comment]
Otto Mascot
  [11:29 AM](https://microverse-students.slack.com/archives/C04JJTSQS3Z/p1673951383539139)
Hi @channel,
We are sorry to let you know that Dennis will be leaving your team today. If this has come as a surprise or if you think you might struggle to complete the week without Dennis, please reachout to [Student Success](mailto:success@microverse.org) so that we can support you. This is especially important if your project requires collaboration.
Otto

**Review by rustam-tolipov — APPROVED** [review]
Hi @djo1975, and @julie-ify, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Developer-512px-10

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯

## Optional suggestions
Kindly add the MIT license to your readme :)

Also, you are free to remove this line from your readme:

> NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
